/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package knockgamedemo;
import java.util.*;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * @author Administrator
 */
public class GameJFrame extends javax.swing.JFrame {

    private ArrayList<JButton> buttonArray;
    private int currentIndex;
    private int score;
    private Timer timer;
    private Random rd;
        
    /**
     * Creates new form GameJFrame
     */
    public GameJFrame() {
        initComponents();
        this.setSize(660,660);
        this.setResizable(false);
        buttonArray=new ArrayList<>();
        for(int i=0;i<9;i++)
        {
            JButton button=new JButton(new ImageIcon("background.png"));
            button.setSize(220,220);
            button.addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    knocknock(e);
                }
            });
            buttonArray.add(button);
            this.add(button);            
        }
        rd=new Random();
        currentIndex=rd.nextInt(9);
        buttonArray.get(currentIndex).setIcon(new ImageIcon("mouse.png"));
        timer=new Timer(200,new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
               changeLocation();
            }
        
        });
        timer.start();
        
    }

    private  void knocknock(ActionEvent e)
    {
        JButton knockButton=(JButton)e.getSource();
        JButton currentButton=buttonArray.get(currentIndex);
        if(knockButton.equals(currentButton))
        {
            score+=10;
            this.setTitle("您的得分是："+score);
        }
    }
    private void changeLocation()
    {
        buttonArray.get(currentIndex).setIcon(new ImageIcon("background.png"));
        currentIndex=rd.nextInt(9);
        buttonArray.get(currentIndex).setIcon(new ImageIcon("mouse.png"));
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(3, 3));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
